require("core.global")
require("core.keymap")
require("core.lsp")
require("core.option")

require("module.column-guide").setup({})
require("module.explorer").setup({})
require("module.indent-guide").setup({})
require("module.picker").setup({})
require("module.statusline").setup({})
require("module.tabline").setup({})
require("module.terminal").setup({})
require("module.theme").setup({})
